ALTER TABLE DICT.Sex ADD CONSTRAINT Sex_PK PRIMARY KEY CLUSTERED (SexId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DICT.Sex ADD CONSTRAINT Sex_Name_UN UNIQUE NONCLUSTERED (Name)
GO