ALTER TABLE DICT.LocationTypes ADD CONSTRAINT LocationTypes_PK PRIMARY KEY CLUSTERED (TypeID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DICT.LocationTypes ADD CONSTRAINT LocationTypes_TypeName_UN UNIQUE NONCLUSTERED (TypeName)
GO