ALTER TABLE DICT.VehicleModel ADD CONSTRAINT VehicleModel_PK PRIMARY KEY CLUSTERED (ModelId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE DICT.VehicleModel ADD CONSTRAINT VehicleModel_ModelName_UN UNIQUE NONCLUSTERED (ModelName)
GO