ALTER TABLE FLEET.VehicleItem ADD CONSTRAINT VehicleItem_PK PRIMARY KEY CLUSTERED (VehicleID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE FLEET.VehicleItem ADD CONSTRAINT VehicleItem_ModelId_SerialNumber_YearOfIssue_UN UNIQUE NONCLUSTERED (ModelId, SerialNumber, YearOfIssue)
GO
ALTER TABLE FLEET.VehicleItem ADD CONSTRAINT VehicleItem_RegNumber_IsActive_UN UNIQUE NONCLUSTERED (RegNumber, IsActive)
GO

ALTER TABLE FLEET.VehicleItem ADD CONSTRAINT VEHICLE_ITEM_CK_YEAR_OF_ISSUE CHECK ( YearOfIssue > 1950 ) 
GO


ALTER TABLE FLEET.VehicleItem ADD CONSTRAINT VEHICLE_ITEM_CK_GUARANTEE_PERIOD CHECK ( GuaranteePeriod > DATEADD(year,1, GETDATE())  ) 
GO


ALTER TABLE FLEET.VehicleItem ADD CONSTRAINT VEHICLE_ITEM_CK_MAX_MILEAGE CHECK ( MaxTotalMileage > 1000 ) 
GO