ALTER TABLE FLEET.Driver ADD CONSTRAINT Driver_PK PRIMARY KEY CLUSTERED (DriverId)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE FLEET.Driver ADD CONSTRAINT DriverUN UNIQUE NONCLUSTERED (PersonId, CatId, DocId)
GO