ALTER TABLE PLANS.Route ADD CONSTRAINT Route_PK PRIMARY KEY CLUSTERED (RouteID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE PLANS.Route ADD CONSTRAINT Route_FromLocationID_ToLocationID_UN UNIQUE NONCLUSTERED (FromLocationId, ToLocationId)
GO

ALTER TABLE PLANS.Route ADD CONSTRAINT Route_From_TO_CK CHECK ( FromLocationId <> ToLocationId ) 
GO


ALTER TABLE PLANS.Route ADD CONSTRAINT Route_Length_CK CHECK ( RouteLength > 0 ) 
GO


ALTER TABLE PLANS.Route ADD CONSTRAINT Route_Time_CK CHECK ( TimeToDriveEst > 0 ) 
GO