@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Schema\DICT.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Schema\FLEET.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Schema\PLANS.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Schema\REG.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Schema\TRANS.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\FLEET.Driver.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\FLEET.Driver_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.IdentityDocType.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.IdentityDocType_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\REG.IdentityDocument.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\REG.IdentityDocument_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.Location.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.Location_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.LocationTypes.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.LocationTypes_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\REG.Person.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\REG.Person_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\PLANS.Route.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\PLANS.Route_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\PLANS.ScheduledTrips.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\PLANS.ScheduledTrips_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.SeatsLayoutPlan.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.SeatsLayoutPlan_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.Sex.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.Sex_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.TariffType.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.TariffType_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\TRANS.Tiсket.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\TRANS.Tiсket_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\PLANS.TripStateHistory.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\PLANS.TripStateHistory_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.TripStates.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.TripStates_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.VehicleCathegory.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.VehicleCathegory_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\FLEET.VehicleItem.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\FLEET.VehicleItem_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.VehicleModel.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Table\DICT.VehicleModel_Constraints.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Driver_IdentityDocument_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Driver_Person_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Driver_VehicleCathegory_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\IdentityDocument_IdentityDocType_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\IdentityDocument_Person_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Location_LocationTypes_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Person_Sex_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Route_Location_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Route_Location_FKv2.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\ScheduledTrips_Driver_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\ScheduledTrips_Driver_FKv2v1.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\ScheduledTrips_VehicleItem_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\SeatsLayoutPlan_VehicleModel_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Tiket_Person_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Tiket_SeatsLayoutPlan_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\Tiket_TariffType_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\TripStateHistory_ScheduledTrips_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\TripStateHistory_TripStates_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\TripStates_TripStates_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\VehicleItem_VehicleModel_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\ForeignKey\VehicleModel_VehicleCathegory_FK.sql
@@Vikulin_A.S._(2021-9).DEV-DB.Lab3.v1\Physical_Model\SQL_Server_2012\DataObjects\Sequence\PLANS.TripCodeSeq.sql
